### ISSUE TITLE
Webcast

### ISSUE THREAD

**Issue by Jaom** [fe-dox/bridge-timer#2]
Można zaznaczyć, że wysyła się do internetu i wtedy kontrolowany jest wciąż przez aplikację, ale jest dostępy nie tylko lokalnie ale też z przeglądarki (albo jako zewnętrzny serwis bridgeclo.ck/asdahjg i losowe linki, albo wyniki.turnieju.pl/costam/zegar).

**Comment by smaczka21** [comment]
Z tego co rozmiem to jest w planie
