### ISSUE TITLE
Warianty kolorystyczne / font

### ISSUE THREAD

**Issue by Jaom** [fe-dox/bridge-timer#4]
Skoro to przeglądarkowe, to powinna być opcja custom css i dobre oznaczenie klas tak by user mógł sobie poprawić wygląd .
Jeśli nie to chociaż high contrast opcje powinny być (żółte na niebieskim czy coś) oraz negatyw (białe na czarnym).

**Comment by smaczka21** [comment]
Moim zdaniem to ma najnizszy priorytet ze wszystkiego :p
