### ISSUE TITLE
Wyświetlanie wyników w trakcie

### ISSUE THREAD

**Issue by Jaom** [fe-dox/bridge-timer#8]
Nie wiem czy ktoś korzysta współcześnie, ale było u Jasia, że zegar mógł pokazywać wyniki w trakcie (zwykle np. pół minuty zegar, pół minuty bieżące wyniki "na rzutnik").

Oceniłbym to jako mało ważny feature.

**Comment by smaczka21** [comment]
Moim zdaniem to akurat jest istotne i z tego co rozumiem w planach
